{% set name = "pipdeptree" %}
{% set version = "2.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pipdeptree-{{ version }}.tar.gz
  sha256: 2051bc730fa878846ff3184c1b6b83d348f606cd1a92b9afca9709334d3d0c03

build:
  entry_points:
    - pipdeptree = pipdeptree.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatch-vcs >=0.4
    - hatchling >=1.18
    - pip
  run:
    - packaging >=23.1
    - pip >=23.1.2
    - python >=3.8

test:
  imports:
    - pipdeptree
  commands:
    - pip check
    - pipdeptree --help
  requires:
    - pip

about:
  home: http://github.com/naiquevin/pipdeptree
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Displays installed python packages in form of a dependency tree.
  description: |
    pipdeptree is a command line utility for displaying the
    installed python packages in form of a dependency tree. It works for packages
    installed globally on a machine as well as in a virtualenv. Since pip freeze
    shows all dependencies as a flat list, finding out which are the top level
    packages and which packages do they depend on requires some effort. It can also
    be tedious to resolve conflicting dependencies because pip doesn't yet have
    true dependency resolution (more on this later). This utility tries to solve
    this problem.
  doc_url: https://github.com/naiquevin/pipdeptree
  dev_url: http://github.com/naiquevin/pipdeptree

extra:
  recipe-maintainers:
    - dlqqq
    - cdiener
    - rxm7706
